plugins {
    id "net.fabricmc.fabric-loom" version "1.17.21"
}

group = project.maven_group
version = project.mod_version

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url = "https://maven.fabricmc.net/" }
    exclusiveContent {
        forRepository {
            maven { url = "https://maven.notenoughupdates.org/releases/" }
        }
        filter {
            includeGroup "org.notenoughupdates.moulconfig"
        }
    }
    mavenCentral()
}

loom {
    splitEnvironmentSourceSets()

    mods {
        skyfog {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    implementation "org.notenoughupdates.moulconfig:modern-26.2:4.7.2"
    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.3.20"
    include "org.notenoughupdates.moulconfig:modern-26.2:4.7.2"
    include "org.jetbrains.kotlin:kotlin-stdlib:2.3.20"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    withSourcesJar()
}
